language: node_js
node_js:
  - lts/*
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
stages:
- name: test
- name: build
  if: (branch != master) OR fork
- name: release
  if: (branch = master) AND NOT fork

jobs:
  include:
    - env: TEST="yarn lint:test"
      name: "Style Checks"
      script: yarn lint:test
    - env: TEST="test"
      name: "Unit tests"
      script: yarn test:unit
    - stage: build
      script: yarn build
    - stage: release
      script: yarn build && yarn release
cache: yarn